# Generated by Django 5.2.1 on 2025-11-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursecategory_examcategory_exercisecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'الأولى إعدادي'), ('2', 'الثانية إعدادي'), ('3', 'الثالثة إعدادي')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='season',
            field=models.CharField(blank=True, choices=[('normal', 'الدورة الأولى'), ('retake', 'الدورة الثانية')], max_length=20, null=True, verbose_name='الدورة'),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.examcategory', verbose_name='نوع الامتحان'),
        ),
    ]
