# Generated by Django 5.2.1 on 2025-12-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_document_level_document_season_document_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='season',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='year',
        ),
        migrations.AddField(
            model_name='document',
            name='exam_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_docs', to='courses.examcategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='exercise_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_docs', to='courses.exercisecategory'),
        ),
        migrations.AlterField(
            model_name='document',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
