# Generated by Django 5.2.1 on 2025-12-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_document_category_remove_document_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('1', 'الأولى إعدادي'), ('2', 'الثانية إعدادي'), ('3', 'الثالثة إعدادي')], max_length=1, verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
    ]
