# Generated by Django 5.2.1 on 2025-12-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_description_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursecategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='مضمون الدرس'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='كتب بتاريخ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='course_pdfs/', verbose_name='ملف pdf'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/', verbose_name='الفيديو'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الفيديو'),
        ),
    ]
