# Generated by Django 5.2.1 on 2025-12-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_comment_course_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='exam_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_docs', to='courses.examcategory', verbose_name='صنف الامتحان'),
        ),
        migrations.AlterField(
            model_name='document',
            name='exercise_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_docs', to='courses.exercisecategory', verbose_name='صنف التمرين'),
        ),
        migrations.AlterField(
            model_name='document',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='المستوى'),
        ),
    ]
