# Generated by Django 5.2.1 on 2025-12-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_document_exam_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.course', verbose_name='الدرس'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='كتب بتاريخ'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
    ]
