# Generated by Django 5.2.1 on 2025-12-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_exercise_content_alter_exercise_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
