# Generated by Django 5.2.1 on 2025-12-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_delete_exercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'التعليق', 'verbose_name_plural': 'التعليقات'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'الدرس', 'verbose_name_plural': 'الدروس'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': 'صنف الدرس', 'verbose_name_plural': 'صنف الدرس'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'ملف pdf', 'verbose_name_plural': 'ملفات pdf'},
        ),
        migrations.AlterModelOptions(
            name='examcategory',
            options={'verbose_name': 'صنف الامتحان', 'verbose_name_plural': 'اصناف الامتحانات'},
        ),
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={'verbose_name': 'صنف التمرين', 'verbose_name_plural': 'اصناف التمارين'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'الفيديو', 'verbose_name_plural': 'الفيديوهات'},
        ),
    ]
