# Generated by Django 5.2.1 on 2025-12-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_comment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
